# Generated by Django 5.0.7 on 2024-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Post",
                    models.CharField(
                        blank=True,
                        help_text="Должность",
                        max_length=50,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задания",
                        max_length=100,
                        verbose_name="Название задания",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание задания",
                        verbose_name="Описание задания",
                    ),
                ),
                ("start_time", models.DateField(auto_now_add=True)),
                (
                    "end_time",
                    models.DateField(
                        default="23.09.2024",
                        help_text="Пример: 01.12.2024",
                        verbose_name="Срок выполнения задания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("В работе", "В работе"),
                            ("Завершена", "Завершена"),
                            ("Приостановлена", "Приостановлена"),
                        ],
                        default="Создана",
                        max_length=30,
                        verbose_name="Статус задания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
