# Generated by Django 5.0.7 on 2024-09-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задачи",
                        max_length=100,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание задачи",
                        verbose_name="Описание задачи",
                    ),
                ),
                ("start_time", models.DateField(auto_now_add=True)),
                (
                    "end_time",
                    models.DateField(
                        help_text="Пример: 01-12-2024",
                        verbose_name="Срок выполнения задачи, начала задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("В работе", "В работе"),
                            ("Завершена", "Завершена"),
                            ("Приостановлена", "Приостановлена"),
                        ],
                        default="Создана",
                        max_length=30,
                        verbose_name="Статус задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
