# Generated by Django 5.0.7 on 2024-09-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasktracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель задания",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="Executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Исполнитель задания+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители задания",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="related_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasktracker.task",
                verbose_name="Связанная с другой заданием",
            ),
        ),
    ]
