# Generated by Django 5.0.7 on 2024-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasktracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.DateField(
                default="20.09.2024",
                help_text="Пример: 01-12-2024",
                verbose_name="Срок выполнения задачи",
            ),
        ),
    ]
